#!/usr/bin/env bash
# 
# Copyright (c) Advanced Micro Devices, Inc.
# All rights reserved.
# 

set -e
set -x

tool=$1

# Output filename is tool_output.csv (e.g., gpu_info_power_profiler_output.csv)
OUTPUT=${tool}_output.csv
SAVESPACE=/myworkspace/

cd $SAVESPACE

# Check if prof.csv exists (generated by the profiler)
if [ ! -f "prof.csv" ]; then
    echo "Error: prof.csv not found in $SAVESPACE"
    exit 1
fi

# Move the profiler output to the final location
mv prof.csv "$OUTPUT"

chmod a+rw "${SAVESPACE}/${OUTPUT}"

echo "Profiler output saved to: ${SAVESPACE}/${OUTPUT}"
