#!/usr/bin/env python3
"""
Unit tests for the slurm_multi launcher.

Locks in three contract points so future refactors fail loudly if they regress:
1. `slurm_multi` is registered in `VALID_LAUNCHERS`.
2. `slurm-multi` (hyphen alias) normalizes to `slurm_multi`.
3. The wrapper SBATCH script generated by `_prepare_slurm_multi_script`
   exports every `model_info.env_vars` declared by the model card
   (mirrors the `pyt_sglang_disagg_qwen3-32b_short` entry from MAD-private PR #186).

Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
"""

import json
from pathlib import Path

import pytest

from madengine.deployment.common import VALID_LAUNCHERS, normalize_launcher
from madengine.deployment.base import DeploymentConfig
from madengine.deployment.slurm import SLURM_MULTI_ALIASES, SlurmDeployment


# ---------------------------------------------------------------------------
# 1. Registry membership

class TestSlurmMultiRegistration:
    """slurm_multi is registered in the launcher allowlist."""

    def test_slurm_multi_in_valid_launchers(self):
        assert "slurm_multi" in VALID_LAUNCHERS

    def test_aliases_constant(self):
        assert SLURM_MULTI_ALIASES == ["slurm_multi", "slurm-multi"]


# ---------------------------------------------------------------------------
# 2. Hyphen alias normalization

class TestNormalizeSlurmMultiAliases:
    """slurm-multi (hyphen) normalizes to slurm_multi."""

    def test_canonical(self):
        assert normalize_launcher("slurm_multi", "slurm") == "slurm_multi"

    def test_hyphen_alias(self):
        assert normalize_launcher("slurm-multi", "slurm") == "slurm_multi"

    def test_unknown_falls_through_to_default(self):
        # Sanity: unrelated value still returns docker for slurm
        assert normalize_launcher("totally-bogus", "slurm") == "docker"


# ---------------------------------------------------------------------------
# 3. MAD-private #186 env_vars contract

# Verbatim from MAD-private PR #186, model name pyt_sglang_disagg_qwen3-32b_short.
PR186_MODEL_ENTRY = {
    "name": "pyt_sglang_disagg_qwen3-32b_short",
    "url": "",
    "dockerfile": "docker/sglang_disagg_inference",
    "scripts": "scripts/sglang_disagg/run_xPyD_models.slurm",
    "data": "huggingface",
    "n_gpus": "8",
    "owner": "mad.support@amd.com",
    "training_precision": "",
    "multiple_results": "perf_Qwen3-32B.csv",
    "tags": [
        "pyt", "sglang", "sglang_disagg", "inference",
        "qwen3", "disaggregated", "short",
    ],
    "timeout": -1,
    "args": "--model_name Qwen3-32B --model_path /shared_inference/models_blog/Qwen3-32B --tp_size 8",
    "slurm": {
        "partition": "amd-rccl",
        "nodes": 3,
        "gpus_per_node": 8,
        "time": "01:00:00",
        "output_dir": "./slurm_output",
        "exclusive": True,
        "reservation": "",
    },
    "distributed": {
        "launcher": "slurm_multi",
        "nnodes": 3,
        "nproc_per_node": 8,
        "backend": "nccl",
        "port": 29500,
        "sglang_disagg": {
            "prefill_nodes": 1,
            "decode_nodes": 1,
        },
    },
    "env_vars": {
        "DOCKER_IMAGE_NAME": "rocm/pytorch-private:sglang_disagg_mori_20260502",
        "MODEL_NAME": "Qwen3-32B",
        "MODEL_PATH": "/shared_inference/models_blog/Qwen3-32B",
        "SGLANG_ENABLE_FLASHINFER": "1",
        "SGLANG_ENABLE_RADIX_CACHE": "1",
        "SGLANG_RADIX_CACHE_SIZE": "0.9",
        "xP": "1",
        "yD": "1",
        "BENCHMARK_CONCURRENCY": "8",
        "BENCHMARK_COMBINATIONS": "32/32",
    },
}


class TestSlurmMultiPrepareScript:
    """`_prepare_slurm_multi_script` emits every model_info.env_vars as `export`."""

    @pytest.fixture
    def slurm_deployment(self, tmp_path: Path) -> SlurmDeployment:
        """Build a SlurmDeployment whose manifest contains the MAD-private #186 entry."""
        # _prepare_slurm_multi_script resolves model_info["scripts"] against the
        # manifest's directory and bails (returns False) if the script doesn't exist.
        # Create a placeholder so the existence check passes; contents are irrelevant
        # because prepare() never executes it.
        script_rel = PR186_MODEL_ENTRY["scripts"]
        script_abs = tmp_path / script_rel
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n# placeholder slurm_multi model script for unit test\n")

        # Use the model image-name as the manifest key (matches manifest convention).
        image_key = "rocm/pytorch-private:sglang_disagg_mori_20260502"

        manifest = {
            "built_images": {
                image_key: {
                    "image_name": image_key,
                    "docker_image": image_key,
                    "registry_image": image_key,
                },
            },
            "built_models": {
                image_key: PR186_MODEL_ENTRY,
            },
            "context": {
                "docker_env_vars": {},
                "docker_mounts": {},
                "docker_build_arg": {},
                "gpu_vendor": "AMD",
                "guest_os": "UBUNTU",
                "docker_gpus": "all",
            },
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        # Additional context drives the slurm config: point output_dir at tmp_path
        # so we can read the generated script back.
        additional_context = {
            "deploy": "slurm",
            "gpu_vendor": "AMD",
            "guest_os": "UBUNTU",
            "slurm": dict(PR186_MODEL_ENTRY["slurm"], output_dir=str(tmp_path / "slurm_results")),
            "distributed": PR186_MODEL_ENTRY["distributed"],
        }

        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context=additional_context,
        )
        return SlurmDeployment(cfg)

    def test_prepare_dispatches_to_slurm_multi(self, slurm_deployment, tmp_path):
        """prepare() must take the slurm_multi early-dispatch path and return True."""
        ok = slurm_deployment.prepare()
        assert ok is True
        # Wrapper script should now exist
        assert slurm_deployment.script_path is not None
        assert Path(slurm_deployment.script_path).exists()

    def test_wrapper_exports_all_model_env_vars(self, slurm_deployment):
        """Every key in model_info.env_vars must appear as `export KEY="value"` in the wrapper."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()

        for key, value in PR186_MODEL_ENTRY["env_vars"].items():
            # xP/yD are overridden by distributed.sglang_disagg.{prefill,decode}_nodes
            # in _prepare_slurm_multi_script; values match in this fixture so the
            # assertion still holds, but the source of truth is the model card.
            expected = f'export {key}="{value}"'
            assert expected in script_text, f"missing export for {key!r}: expected {expected!r}"

    def test_wrapper_is_slurm_multi_flag_set(self, slurm_deployment):
        """`_is_slurm_multi` flag must be set so deploy() can choose the bash branch."""
        slurm_deployment.prepare()
        assert getattr(slurm_deployment, "_is_slurm_multi", False) is True

    def test_wrapper_sbatch_header_uses_slurm_config(self, slurm_deployment):
        """SBATCH header reflects the model card's slurm block (partition, nodes, gpus, time, exclusive)."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()
        assert "#SBATCH --partition=amd-rccl" in script_text
        assert "#SBATCH --nodes=3" in script_text
        assert "#SBATCH --gpus-per-node=8" in script_text
        assert "#SBATCH --time=01:00:00" in script_text
        assert "#SBATCH --exclusive" in script_text
        # reservation is "" in the fixture, so no --reservation line
        assert "#SBATCH --reservation=" not in script_text
