#!/usr/bin/env python3
"""
Unit tests for the slurm_multi launcher.

Locks in contract points so future refactors fail loudly if they regress:
1. `slurm_multi` is registered in `VALID_LAUNCHERS`.
2. `slurm-multi` (hyphen alias) normalizes to `slurm_multi`.
3. The wrapper SBATCH script generated by `_prepare_slurm_multi_script`
   exports every `model_info.env_vars` declared by the model card
   (mirrors the `pyt_sglang_disagg_qwen3-32b_short` entry from MAD-private PR #186).
4. The wrapper bash invocation is wrapped in `set +e` / `set -e` so a non-zero
   exit from the model script does not skip the completion-marker write.
5. `_execute_with_prebuilt_image` produces a manifest where `built_images.keys()
   == built_models.keys()` so `ContainerRunner.run_models_from_manifest()` joins
   them correctly (also exercises multi-model + nested-dict distributed configs
   to guard against the `tuple(sorted(items()))` unhashable regression).

Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
"""

import json
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from madengine.deployment.common import VALID_LAUNCHERS, is_self_managed_launcher, normalize_launcher
from madengine.deployment.base import DeploymentConfig
from madengine.deployment.slurm import SlurmDeployment


# ---------------------------------------------------------------------------
# 1. Registry membership

class TestSlurmMultiRegistration:
    """slurm_multi is registered in the launcher allowlist."""

    def test_slurm_multi_in_valid_launchers(self):
        assert "slurm_multi" in VALID_LAUNCHERS

    @pytest.mark.parametrize("launcher,expected", [
        ("slurm_multi", True),
        ("slurm-multi", True),   # hyphen alias normalized via normalize_launcher
        ("torchrun", False),
        ("vllm", False),
        ("sglang-disagg", False),
        ("", False),
        (None, False),
    ])
    def test_is_self_managed_launcher(self, launcher, expected):
        """is_self_managed_launcher must accept both aliases and reject all other launchers."""
        assert is_self_managed_launcher(launcher) is expected


# ---------------------------------------------------------------------------
# 2. Hyphen alias normalization

class TestNormalizeSlurmMultiAliases:
    """slurm-multi (hyphen) normalizes to slurm_multi."""

    def test_canonical(self):
        assert normalize_launcher("slurm_multi", "slurm") == "slurm_multi"

    def test_hyphen_alias(self):
        assert normalize_launcher("slurm-multi", "slurm") == "slurm_multi"

    def test_unknown_falls_through_to_default(self):
        # Sanity: unrelated value still returns docker for slurm
        assert normalize_launcher("totally-bogus", "slurm") == "docker"


# ---------------------------------------------------------------------------
# 3. MAD-private #186 env_vars contract

# Verbatim from MAD-private PR #186, model name pyt_sglang_disagg_qwen3-32b_short.
PR186_MODEL_ENTRY = {
    "name": "pyt_sglang_disagg_qwen3-32b_short",
    "url": "",
    "dockerfile": "docker/sglang_disagg_inference",
    "scripts": "scripts/sglang_disagg/run_xPyD_models.slurm",
    "data": "huggingface",
    "n_gpus": "8",
    "owner": "mad.support@amd.com",
    "training_precision": "",
    "multiple_results": "perf_Qwen3-32B.csv",
    "tags": [
        "pyt", "sglang", "sglang_disagg", "inference",
        "qwen3", "disaggregated", "short",
    ],
    "timeout": -1,
    "args": "--model_name Qwen3-32B --model_path /shared_inference/models_blog/Qwen3-32B --tp_size 8",
    "slurm": {
        "partition": "amd-rccl",
        "nodes": 3,
        "gpus_per_node": 8,
        "time": "01:00:00",
        "output_dir": "./slurm_output",
        "exclusive": True,
        "reservation": "",
    },
    "distributed": {
        "launcher": "slurm_multi",
        "nnodes": 3,
        "nproc_per_node": 8,
        "backend": "nccl",
        "port": 29500,
        "sglang_disagg": {
            "prefill_nodes": 1,
            "decode_nodes": 1,
        },
    },
    "env_vars": {
        "DOCKER_IMAGE_NAME": "rocm/pytorch-private:sglang_disagg_mori_20260502",
        "MODEL_NAME": "Qwen3-32B",
        "MODEL_PATH": "/shared_inference/models_blog/Qwen3-32B",
        "SGLANG_ENABLE_FLASHINFER": "1",
        "SGLANG_ENABLE_RADIX_CACHE": "1",
        "SGLANG_RADIX_CACHE_SIZE": "0.9",
        "xP": "1",
        "yD": "1",
        "BENCHMARK_CONCURRENCY": "8",
        "BENCHMARK_COMBINATIONS": "32/32",
    },
}


class TestSlurmMultiPrepareScript:
    """`_prepare_slurm_multi_script` emits every model_info.env_vars as `export`."""

    @pytest.fixture
    def slurm_deployment(self, tmp_path: Path) -> SlurmDeployment:
        """Build a SlurmDeployment whose manifest contains the MAD-private #186 entry."""
        # _prepare_slurm_multi_script resolves model_info["scripts"] against the
        # manifest's directory and bails (returns False) if the script doesn't exist.
        # Create a placeholder so the existence check passes; contents are irrelevant
        # because prepare() never executes it.
        script_rel = PR186_MODEL_ENTRY["scripts"]
        script_abs = tmp_path / script_rel
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n# placeholder slurm_multi model script for unit test\n")

        # Use the model image-name as the manifest key (matches manifest convention).
        image_key = "rocm/pytorch-private:sglang_disagg_mori_20260502"

        manifest = {
            "built_images": {
                image_key: {
                    "image_name": image_key,
                    "docker_image": image_key,
                    "registry_image": image_key,
                },
            },
            "built_models": {
                image_key: PR186_MODEL_ENTRY,
            },
            "context": {
                "docker_env_vars": {},
                "docker_mounts": {},
                "docker_build_arg": {},
                "gpu_vendor": "AMD",
                "guest_os": "UBUNTU",
                "docker_gpus": "all",
            },
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        # Additional context drives the slurm config: point output_dir at tmp_path
        # so we can read the generated script back.
        additional_context = {
            "deploy": "slurm",
            "gpu_vendor": "AMD",
            "guest_os": "UBUNTU",
            "slurm": dict(PR186_MODEL_ENTRY["slurm"], output_dir=str(tmp_path / "slurm_results")),
            "distributed": PR186_MODEL_ENTRY["distributed"],
        }

        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context=additional_context,
        )
        return SlurmDeployment(cfg)

    def test_prepare_dispatches_to_slurm_multi(self, slurm_deployment, tmp_path):
        """prepare() must take the slurm_multi early-dispatch path and return True."""
        ok = slurm_deployment.prepare()
        assert ok is True
        # Wrapper script should now exist
        assert slurm_deployment.script_path is not None
        assert Path(slurm_deployment.script_path).exists()

    def test_wrapper_exports_all_model_env_vars(self, slurm_deployment):
        """Every key in model_info.env_vars must appear as `export KEY="value"` in the wrapper."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()

        for key, value in PR186_MODEL_ENTRY["env_vars"].items():
            # xP/yD are overridden by distributed.sglang_disagg.{prefill,decode}_nodes
            # in _prepare_slurm_multi_script; values match in this fixture so the
            # assertion still holds, but the source of truth is the model card.
            expected = f'export {key}="{value}"'
            assert expected in script_text, f"missing export for {key!r}: expected {expected!r}"

    def test_wrapper_is_slurm_multi_flag_set(self, slurm_deployment):
        """`_is_slurm_multi` flag must be set so deploy() can choose the bash branch."""
        slurm_deployment.prepare()
        assert getattr(slurm_deployment, "_is_slurm_multi", False) is True

    def test_wrapper_sbatch_header_uses_slurm_config(self, slurm_deployment):
        """SBATCH header reflects the model card's slurm block (partition, nodes, gpus, time, exclusive)."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()
        assert "#SBATCH --partition=amd-rccl" in script_text
        assert "#SBATCH --nodes=3" in script_text
        assert "#SBATCH --gpus-per-node=8" in script_text
        assert "#SBATCH --time=01:00:00" in script_text
        assert "#SBATCH --exclusive" in script_text
        # reservation is "" in the fixture, so no --reservation line
        assert "#SBATCH --reservation=" not in script_text

    def test_wrapper_disables_set_e_around_model_script(self, slurm_deployment):
        """Regression for Copilot C6: `set -e` at the top of the wrapper would
        terminate the script before SCRIPT_EXIT_CODE is captured and the
        completion marker is written if the model script exits non-zero.
        The wrapper must `set +e` immediately before the bash invocation,
        capture $?, then re-enable `set -e` before continuing."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()

        # Find the index of the bash <model_script> line and assert the
        # surrounding set +e / SCRIPT_EXIT_CODE / set -e ordering.
        lines = script_text.splitlines()
        bash_line_idx = next(
            (i for i, line in enumerate(lines) if line.strip().startswith("bash run_xPyD_models.slurm")),
            None,
        )
        assert bash_line_idx is not None, "wrapper must invoke the model script via bash"

        # The two preceding non-empty/non-comment lines must include `set +e`
        prelude = [l.strip() for l in lines[max(0, bash_line_idx - 5):bash_line_idx] if l.strip() and not l.strip().startswith("#")]
        assert "set +e" in prelude, (
            f"`set +e` must appear immediately before bash invocation, got prelude {prelude!r}"
        )

        # SCRIPT_EXIT_CODE must be captured immediately after, and -e re-enabled before exit
        suffix = [l.strip() for l in lines[bash_line_idx + 1:bash_line_idx + 5] if l.strip() and not l.strip().startswith("#")]
        assert suffix[0] == "SCRIPT_EXIT_CODE=$?", f"first non-comment line after bash must capture $?, got {suffix!r}"
        assert "set -e" in suffix, f"`set -e` must be re-enabled after capture, got {suffix!r}"

        # And the final exit must use the captured exit code
        assert "exit $SCRIPT_EXIT_CODE" in script_text


# ---------------------------------------------------------------------------
# 4. _execute_with_prebuilt_image manifest-shape contract (Copilot C2 + C3)

class TestPrebuiltImageManifestShape:
    """Regression tests for the manifest produced by `_execute_with_prebuilt_image`.

    Two invariants the rest of the codebase relies on:
    - C2: `built_images.keys() == built_models.keys()` so
      `ContainerRunner.run_models_from_manifest()` can join them via
      `built_models.get(image_name, {})`.
    - C3: discovering >1 model whose `distributed` block contains nested dicts
      (e.g. `sglang_disagg`, `vllm_disagg`) must not raise
      `TypeError: unhashable type: 'dict'` when comparing distinct configs.
    """

    @pytest.fixture
    def fake_models_two_sglang_disagg(self):
        """Two sglang_disagg model cards. `distributed` includes a nested dict
        (sglang_disagg.{prefill_nodes, decode_nodes}) so `tuple(sorted(items()))`
        on this would TypeError -- exactly what C3 protects against."""
        common_distributed = {
            "launcher": "slurm_multi",
            "nnodes": 3,
            "nproc_per_node": 8,
            "backend": "nccl",
            "port": 29500,
            "sglang_disagg": {"prefill_nodes": 1, "decode_nodes": 1},
        }
        common_slurm = {
            "partition": "amd-rccl",
            "nodes": 3,
            "gpus_per_node": 8,
            "time": "01:00:00",
            "exclusive": True,
            "reservation": "",
        }
        return [
            {
                "name": "pyt_fake_a",
                "dockerfile": "docker/sglang_disagg_inference",
                "scripts": "scripts/fake/run.sh",
                "n_gpus": "8",
                "owner": "test@amd.com",
                "tags": ["pyt", "fake", "a"],
                "args": "--model_a",
                "slurm": common_slurm,
                "distributed": common_distributed,
                "env_vars": {"MODEL_NAME": "Fake-A"},
            },
            {
                "name": "pyt_fake_b",
                "dockerfile": "docker/sglang_disagg_inference",
                "scripts": "scripts/fake/run.sh",
                "n_gpus": "8",
                "owner": "test@amd.com",
                "tags": ["pyt", "fake", "b"],
                "args": "--model_b",
                "slurm": common_slurm,
                # Differing nested-dict to trigger the warning + dedup path
                "distributed": {**common_distributed, "sglang_disagg": {"prefill_nodes": 2, "decode_nodes": 1}},
                "env_vars": {"MODEL_NAME": "Fake-B"},
            },
        ]

    def _build_orchestrator_stub(self, tmp_path: Path):
        """Construct a BuildOrchestrator instance with `__new__` so we skip the
        real constructor (which initializes Context, ConfigLoader, credentials,
        etc.). We populate only the attributes `_execute_with_prebuilt_image`
        and `_save_deployment_config` actually read."""
        from madengine.orchestration.build_orchestrator import BuildOrchestrator
        orch = BuildOrchestrator.__new__(BuildOrchestrator)
        # Required attributes
        orch.args = MagicMock()
        orch.console = MagicMock()
        orch.rich_console = MagicMock()
        orch.context = MagicMock()
        orch.context.ctx = {"docker_env_vars": {}, "docker_mounts": {}}
        orch.additional_context = {}
        orch._original_user_slurm_keys = set()
        orch.credentials = {}
        return orch

    def test_built_images_and_models_share_keys(self, tmp_path, fake_models_two_sglang_disagg):
        """Copilot C2: built_images and built_models must use the same keys
        (model_name) so ContainerRunner.run_models_from_manifest() finds
        each model_info via `built_models.get(image_name, {})`."""
        orch = self._build_orchestrator_stub(tmp_path)
        manifest_path = tmp_path / "build_manifest.json"
        use_image = "rocm/pytorch-private:fake-tag"

        with patch("madengine.orchestration.build_orchestrator.DiscoverModels") as mock_dm:
            mock_dm.return_value.run.return_value = fake_models_two_sglang_disagg
            # _save_deployment_config writes a sidecar file we don't care about;
            # patch it to a no-op so we don't depend on its filesystem behavior.
            with patch.object(orch, "_save_deployment_config", return_value=None):
                orch._execute_with_prebuilt_image(use_image=use_image, manifest_output=str(manifest_path))

        manifest = json.loads(manifest_path.read_text())

        assert set(manifest["built_images"].keys()) == set(manifest["built_models"].keys()), (
            "built_images and built_models must share the same key set"
        )
        assert set(manifest["built_models"].keys()) == {"pyt_fake_a", "pyt_fake_b"}

        for model_name in ("pyt_fake_a", "pyt_fake_b"):
            assert manifest["built_images"][model_name]["docker_image"] == use_image
            assert manifest["built_images"][model_name]["prebuilt"] is True
            assert manifest["built_models"][model_name]["env_vars"]["DOCKER_IMAGE_NAME"] == use_image

    def test_multi_model_nested_dict_distributed_does_not_raise(
        self, tmp_path, fake_models_two_sglang_disagg
    ):
        """Copilot C3: `distinct_distributed` / `distinct_slurm` dedupe must not
        TypeError when distributed/slurm blocks contain nested dicts. Before
        the fix, `tuple(sorted((m.get('distributed') or {}).items()))` raised
        `TypeError: unhashable type: 'dict'` because the dict values aren't
        hashable when stuffed into a set."""
        orch = self._build_orchestrator_stub(tmp_path)
        manifest_path = tmp_path / "build_manifest.json"

        with patch("madengine.orchestration.build_orchestrator.DiscoverModels") as mock_dm:
            mock_dm.return_value.run.return_value = fake_models_two_sglang_disagg
            with patch.object(orch, "_save_deployment_config", return_value=None):
                # Must not raise TypeError
                orch._execute_with_prebuilt_image(
                    use_image="rocm/pytorch-private:fake-tag",
                    manifest_output=str(manifest_path),
                )

        # Manifest should still be valid JSON with both models present
        manifest = json.loads(manifest_path.read_text())
        assert len(manifest["built_models"]) == 2


# ---------------------------------------------------------------------------
# 5. xP/yD skip-if-set: model card wins over distributed.sglang_disagg

class TestXpYdSkipIfSet:
    """xP/yD in model card env_vars must not be overwritten by distributed.sglang_disagg."""

    @pytest.fixture
    def slurm_deployment(self, tmp_path: Path) -> SlurmDeployment:
        """SlurmDeployment with model card that has xP=2/yD=3 while sglang_disagg says 1/1."""
        model_info = {
            **PR186_MODEL_ENTRY,
            "env_vars": {**PR186_MODEL_ENTRY["env_vars"], "xP": "2", "yD": "3"},
            "distributed": {
                **PR186_MODEL_ENTRY["distributed"],
                "sglang_disagg": {"prefill_nodes": 1, "decode_nodes": 1},
            },
        }
        script_abs = tmp_path / PR186_MODEL_ENTRY["scripts"]
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n")

        image_key = "rocm/pytorch-private:sglang_disagg_mori_20260502"
        manifest = {
            "built_images": {image_key: {"image_name": image_key, "docker_image": image_key}},
            "built_models": {image_key: model_info},
            "context": {
                "docker_env_vars": {}, "docker_mounts": {}, "docker_build_arg": {},
                "gpu_vendor": "AMD", "guest_os": "UBUNTU", "docker_gpus": "all",
            },
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        additional_context = {
            "deploy": "slurm",
            "gpu_vendor": "AMD",
            "guest_os": "UBUNTU",
            "slurm": dict(PR186_MODEL_ENTRY["slurm"], output_dir=str(tmp_path / "slurm_results")),
            "distributed": model_info["distributed"],
        }
        cfg = DeploymentConfig(target="slurm", manifest_file=str(manifest_path),
                               additional_context=additional_context)
        return SlurmDeployment(cfg)

    def test_model_card_xp_yd_wins(self, slurm_deployment):
        """When env_vars already contains xP/yD, distributed.sglang_disagg must not override them."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()

        assert 'export xP="2"' in script_text, "model card xP=2 must not be overwritten"
        assert 'export yD="3"' in script_text, "model card yD=3 must not be overwritten"
        assert 'export xP="1"' not in script_text, "distributed.sglang_disagg xP=1 must not win"
        assert 'export yD="1"' not in script_text, "distributed.sglang_disagg yD=1 must not win"


# ---------------------------------------------------------------------------
# 6. _execute_build_on_compute manifest-shape contract (multi-model parity)

class TestBuildOnComputeManifestShape:
    """_execute_build_on_compute must produce the same key contract as _execute_with_prebuilt_image.

    built_images.keys() == built_models.keys() == set of model names, so
    ContainerRunner.run_models_from_manifest() can join them.
    """

    def _build_orchestrator_stub(self, tmp_path: Path):
        from madengine.orchestration.build_orchestrator import BuildOrchestrator
        orch = BuildOrchestrator.__new__(BuildOrchestrator)
        orch.args = MagicMock()
        orch.console = MagicMock()
        orch.rich_console = MagicMock()
        orch.context = MagicMock()
        orch.context.ctx = {}
        orch.additional_context = {"slurm": {"partition": "gpu", "time": "01:00:00"}}
        orch._original_user_slurm_keys = set()
        orch.credentials = {}
        return orch

    def test_two_model_manifest_keys_match(self, tmp_path):
        """built_images and built_models must share the same key set (model names)."""
        fake_models = [
            {
                "name": "model_a",
                "dockerfile": "docker/model_a",
                "scripts": "scripts/model_a/run.sh",
                "n_gpus": "8",
                "tags": ["model_a"],
                "slurm": {"partition": "gpu", "time": "01:00:00"},
                "distributed": {"launcher": "slurm_multi"},
                "env_vars": {},
            },
            {
                "name": "model_b",
                "dockerfile": "docker/model_b",
                "scripts": "scripts/model_b/run.sh",
                "n_gpus": "8",
                "tags": ["model_b"],
                "slurm": {"partition": "gpu", "time": "01:00:00"},
                "distributed": {"launcher": "slurm_multi"},
                "env_vars": {},
            },
        ]
        # Write dummy Dockerfiles so glob finds them
        for m in fake_models:
            df = tmp_path / f"{m['dockerfile']}.ubuntu.amd.Dockerfile"
            df.parent.mkdir(parents=True, exist_ok=True)
            df.write_text("FROM scratch\n")

        manifest_path = tmp_path / "build_manifest.json"
        orch = self._build_orchestrator_stub(tmp_path)

        import os
        orig_cwd = os.getcwd()
        try:
            os.chdir(tmp_path)
            with patch("madengine.orchestration.build_orchestrator.DiscoverModels") as mock_dm:
                mock_dm.return_value.run.return_value = fake_models
                with patch("subprocess.run") as mock_run:
                    mock_run.return_value = MagicMock(returncode=0)
                    # Use localhost:5000 (private-registry path) so the test
                    # doesn't hit the public-registry credential gate at
                    # build_orchestrator.py:954. The manifest-shape contract
                    # this test locks in is registry-agnostic.
                    orch._execute_build_on_compute(
                        registry="localhost:5000/myrepo",
                        manifest_output=str(manifest_path),
                    )
        finally:
            os.chdir(orig_cwd)

        manifest = json.loads(manifest_path.read_text())
        assert set(manifest["built_images"].keys()) == set(manifest["built_models"].keys()), (
            "built_images and built_models must share the same key set"
        )
        assert set(manifest["built_models"].keys()) == {"model_a", "model_b"}
        for mn in ("model_a", "model_b"):
            assert manifest["built_models"][mn]["built_on_compute"] is True
            assert "DOCKER_IMAGE_NAME" in manifest["built_models"][mn]["env_vars"]
