#!/usr/bin/env python3
"""
Unit tests for the slurm_multi launcher.

Locks in contract points so future refactors fail loudly if they regress:
1. `slurm_multi` is registered in `VALID_LAUNCHERS`.
2. `slurm-multi` (hyphen alias) normalizes to `slurm_multi`.
3. The wrapper SBATCH script generated by `_prepare_slurm_multi_script`
   exports every `model_info.env_vars` declared by the model card
   (mirrors the `pyt_sglang_disagg_qwen3-32b_short` entry from MAD-private PR #186).
4. The wrapper bash invocation is wrapped in `set +e` / `set -e` so a non-zero
   exit from the model script does not skip the completion-marker write.
5. `_execute_with_prebuilt_image` produces a manifest where `built_images.keys()
   == built_models.keys()` so `ContainerRunner.run_models_from_manifest()` joins
   them correctly (also exercises multi-model + nested-dict distributed configs
   to guard against the `tuple(sorted(items()))` unhashable regression).

Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
"""

import json
import shlex
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from madengine.deployment.common import VALID_LAUNCHERS, is_self_managed_launcher, normalize_launcher
from madengine.deployment.base import DeploymentConfig
from madengine.deployment.slurm import SlurmDeployment
from madengine.core.errors import ConfigurationError


# ---------------------------------------------------------------------------
# 1. Registry membership

class TestSlurmMultiRegistration:
    """slurm_multi is registered in the launcher allowlist."""

    def test_slurm_multi_in_valid_launchers(self):
        assert "slurm_multi" in VALID_LAUNCHERS

    @pytest.mark.parametrize("launcher,expected", [
        ("slurm_multi", True),
        ("slurm-multi", True),   # hyphen alias normalized via normalize_launcher
        ("torchrun", False),
        ("vllm", False),
        ("sglang-disagg", False),
        ("", False),
        (None, False),
    ])
    def test_is_self_managed_launcher(self, launcher, expected):
        """is_self_managed_launcher must accept both aliases and reject all other launchers."""
        assert is_self_managed_launcher(launcher) is expected


# ---------------------------------------------------------------------------
# 2. Hyphen alias normalization

class TestNormalizeSlurmMultiAliases:
    """slurm-multi (hyphen) normalizes to slurm_multi."""

    def test_canonical(self):
        assert normalize_launcher("slurm_multi", "slurm") == "slurm_multi"

    def test_hyphen_alias(self):
        assert normalize_launcher("slurm-multi", "slurm") == "slurm_multi"

    def test_unknown_falls_through_to_default(self):
        # Sanity: unrelated value still returns docker for slurm
        assert normalize_launcher("totally-bogus", "slurm") == "docker"


# ---------------------------------------------------------------------------
# 3. MAD-private #186 env_vars contract

# Verbatim from MAD-private PR #186, model name pyt_sglang_disagg_qwen3-32b_short.
PR186_MODEL_ENTRY = {
    "name": "pyt_sglang_disagg_qwen3-32b_short",
    "url": "",
    "dockerfile": "docker/sglang_disagg_inference",
    "scripts": "scripts/sglang_disagg/run_xPyD_models.slurm",
    "data": "huggingface",
    "n_gpus": "8",
    "owner": "mad.support@amd.com",
    "training_precision": "",
    "multiple_results": "perf_Qwen3-32B.csv",
    "tags": [
        "pyt", "sglang", "sglang_disagg", "inference",
        "qwen3", "disaggregated", "short",
    ],
    "timeout": -1,
    "args": "--model_name Qwen3-32B --model_path /shared_inference/models_blog/Qwen3-32B --tp_size 8",
    "slurm": {
        "partition": "amd-rccl",
        "nodes": 3,
        "gpus_per_node": 8,
        "time": "01:00:00",
        "output_dir": "./slurm_output",
        "exclusive": True,
        "reservation": "",
    },
    "distributed": {
        "launcher": "slurm_multi",
        "nnodes": 3,
        "nproc_per_node": 8,
        "backend": "nccl",
        "port": 29500,
        "sglang_disagg": {
            "prefill_nodes": 1,
            "decode_nodes": 1,
        },
    },
    "env_vars": {
        "DOCKER_IMAGE_NAME": "rocm/pytorch-private:sglang_disagg_mori_20260502",
        "MODEL_NAME": "Qwen3-32B",
        "MODEL_PATH": "/shared_inference/models_blog/Qwen3-32B",
        "SGLANG_ENABLE_FLASHINFER": "1",
        "SGLANG_ENABLE_RADIX_CACHE": "1",
        "SGLANG_RADIX_CACHE_SIZE": "0.9",
        "xP": "1",
        "yD": "1",
        "BENCHMARK_CONCURRENCY": "8",
        "BENCHMARK_COMBINATIONS": "32/32",
    },
}


class TestSlurmMultiPrepareScript:
    """`_prepare_slurm_multi_script` emits every model_info.env_vars as `export`."""

    @pytest.fixture
    def slurm_deployment(self, tmp_path: Path) -> SlurmDeployment:
        """Build a SlurmDeployment whose manifest contains the MAD-private #186 entry."""
        # _prepare_slurm_multi_script resolves model_info["scripts"] against the
        # manifest's directory and bails (returns False) if the script doesn't exist.
        # Create a placeholder so the existence check passes; contents are irrelevant
        # because prepare() never executes it.
        script_rel = PR186_MODEL_ENTRY["scripts"]
        script_abs = tmp_path / script_rel
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n# placeholder slurm_multi model script for unit test\n")

        # Use the model image-name as the manifest key (matches manifest convention).
        image_key = "rocm/pytorch-private:sglang_disagg_mori_20260502"

        manifest = {
            "built_images": {
                image_key: {
                    "image_name": image_key,
                    "docker_image": image_key,
                    "registry_image": image_key,
                },
            },
            "built_models": {
                image_key: PR186_MODEL_ENTRY,
            },
            "context": {
                "docker_env_vars": {},
                "docker_mounts": {},
                "docker_build_arg": {},
                "gpu_vendor": "AMD",
                "guest_os": "UBUNTU",
                "docker_gpus": "all",
            },
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        # Additional context drives the slurm config: point output_dir at tmp_path
        # so we can read the generated script back.
        additional_context = {
            "deploy": "slurm",
            "gpu_vendor": "AMD",
            "guest_os": "UBUNTU",
            "slurm": dict(PR186_MODEL_ENTRY["slurm"], output_dir=str(tmp_path / "slurm_results")),
            "distributed": PR186_MODEL_ENTRY["distributed"],
        }

        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context=additional_context,
        )
        return SlurmDeployment(cfg)

    def test_prepare_dispatches_to_slurm_multi(self, slurm_deployment, tmp_path):
        """prepare() must take the slurm_multi early-dispatch path and return True."""
        ok = slurm_deployment.prepare()
        assert ok is True
        # Wrapper script should now exist
        assert slurm_deployment.script_path is not None
        assert Path(slurm_deployment.script_path).exists()

    def test_wrapper_exports_all_model_env_vars(self, slurm_deployment):
        """Every key in model_info.env_vars must appear as `export KEY="value"` in the wrapper."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()

        for key, value in PR186_MODEL_ENTRY["env_vars"].items():
            # xP/yD are overridden by distributed.sglang_disagg.{prefill,decode}_nodes
            # in _prepare_slurm_multi_script; values match in this fixture so the
            # assertion still holds, but the source of truth is the model card.
            expected = f"export {key}={shlex.quote(str(value))}"
            assert expected in script_text, f"missing export for {key!r}: expected {expected!r}"

    def test_wrapper_is_slurm_multi_flag_set(self, slurm_deployment):
        """`_is_slurm_multi` flag must be set so deploy() can choose the bash branch."""
        slurm_deployment.prepare()
        assert getattr(slurm_deployment, "_is_slurm_multi", False) is True

    def test_wrapper_sbatch_header_uses_slurm_config(self, slurm_deployment):
        """SBATCH header reflects the model card's slurm block (partition, nodes, gpus, time, exclusive)."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()
        assert "#SBATCH --partition=amd-rccl" in script_text
        assert "#SBATCH --nodes=3" in script_text
        assert "#SBATCH --gpus-per-node=8" in script_text
        assert "#SBATCH --time=01:00:00" in script_text
        assert "#SBATCH --exclusive" in script_text
        # reservation is "" in the fixture, so no --reservation line
        assert "#SBATCH --reservation=" not in script_text

    def test_wrapper_disables_set_e_around_model_script(self, slurm_deployment):
        """Regression for Copilot C6: `set -e` at the top of the wrapper would
        terminate the script before SCRIPT_EXIT_CODE is captured and the
        completion marker is written if the model script exits non-zero.
        The wrapper must `set +e` immediately before the bash invocation,
        capture $?, then re-enable `set -e` before continuing."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()

        # Find the index of the bash <model_script> line and assert the
        # surrounding set +e / SCRIPT_EXIT_CODE / set -e ordering.
        lines = script_text.splitlines()
        bash_line_idx = next(
            (i for i, line in enumerate(lines) if line.strip().startswith("bash run_xPyD_models.slurm")),
            None,
        )
        assert bash_line_idx is not None, "wrapper must invoke the model script via bash"

        # The two preceding non-empty/non-comment lines must include `set +e`
        prelude = [l.strip() for l in lines[max(0, bash_line_idx - 5):bash_line_idx] if l.strip() and not l.strip().startswith("#")]
        assert "set +e" in prelude, (
            f"`set +e` must appear immediately before bash invocation, got prelude {prelude!r}"
        )

        # SCRIPT_EXIT_CODE must be captured immediately after, and -e re-enabled before exit
        suffix = [l.strip() for l in lines[bash_line_idx + 1:bash_line_idx + 5] if l.strip() and not l.strip().startswith("#")]
        assert suffix[0] == "SCRIPT_EXIT_CODE=$?", f"first non-comment line after bash must capture $?, got {suffix!r}"
        assert "set -e" in suffix, f"`set -e` must be re-enabled after capture, got {suffix!r}"

        # And the final exit must use the captured exit code
        assert "exit $SCRIPT_EXIT_CODE" in script_text


# ---------------------------------------------------------------------------
# 4. _execute_with_prebuilt_image manifest-shape contract (Copilot C2 + C3)

class TestPrebuiltImageManifestShape:
    """Regression tests for the manifest produced by `_execute_with_prebuilt_image`.

    Two invariants the rest of the codebase relies on:
    - C2: `built_images.keys() == built_models.keys()` so
      `ContainerRunner.run_models_from_manifest()` can join them via
      `built_models.get(image_name, {})`.
    - C3: discovering >1 model whose `distributed` block contains nested dicts
      (e.g. `sglang_disagg`, `vllm_disagg`) must not raise
      `TypeError: unhashable type: 'dict'` when comparing distinct configs.
    """

    @pytest.fixture
    def fake_models_two_sglang_disagg(self):
        """Two sglang_disagg model cards. `distributed` includes a nested dict
        (sglang_disagg.{prefill_nodes, decode_nodes}) so `tuple(sorted(items()))`
        on this would TypeError -- exactly what C3 protects against."""
        common_distributed = {
            "launcher": "slurm_multi",
            "nnodes": 3,
            "nproc_per_node": 8,
            "backend": "nccl",
            "port": 29500,
            "sglang_disagg": {"prefill_nodes": 1, "decode_nodes": 1},
        }
        common_slurm = {
            "partition": "amd-rccl",
            "nodes": 3,
            "gpus_per_node": 8,
            "time": "01:00:00",
            "exclusive": True,
            "reservation": "",
        }
        return [
            {
                "name": "pyt_fake_a",
                "dockerfile": "docker/sglang_disagg_inference",
                "scripts": "scripts/fake/run.sh",
                "n_gpus": "8",
                "owner": "test@amd.com",
                "tags": ["pyt", "fake", "a"],
                "args": "--model_a",
                "slurm": common_slurm,
                "distributed": common_distributed,
                "env_vars": {"MODEL_NAME": "Fake-A"},
            },
            {
                "name": "pyt_fake_b",
                "dockerfile": "docker/sglang_disagg_inference",
                "scripts": "scripts/fake/run.sh",
                "n_gpus": "8",
                "owner": "test@amd.com",
                "tags": ["pyt", "fake", "b"],
                "args": "--model_b",
                "slurm": common_slurm,
                # Differing nested-dict to trigger the warning + dedup path
                "distributed": {**common_distributed, "sglang_disagg": {"prefill_nodes": 2, "decode_nodes": 1}},
                "env_vars": {"MODEL_NAME": "Fake-B"},
            },
        ]

    def _build_orchestrator_stub(self, tmp_path: Path):
        """Construct a BuildOrchestrator instance with `__new__` so we skip the
        real constructor (which initializes Context, ConfigLoader, credentials,
        etc.). We populate only the attributes `_execute_with_prebuilt_image`
        and `_save_deployment_config` actually read."""
        from madengine.orchestration.build_orchestrator import BuildOrchestrator
        orch = BuildOrchestrator.__new__(BuildOrchestrator)
        # Required attributes
        orch.args = MagicMock()
        orch.console = MagicMock()
        orch.rich_console = MagicMock()
        orch.context = MagicMock()
        orch.context.ctx = {"docker_env_vars": {}, "docker_mounts": {}}
        orch.additional_context = {}
        orch._original_user_slurm_keys = set()
        orch.credentials = {}
        return orch

    def test_built_images_and_models_share_keys(self, tmp_path, fake_models_two_sglang_disagg):
        """Copilot C2: built_images and built_models must use the same keys
        (model_name) so ContainerRunner.run_models_from_manifest() finds
        each model_info via `built_models.get(image_name, {})`."""
        orch = self._build_orchestrator_stub(tmp_path)
        manifest_path = tmp_path / "build_manifest.json"
        use_image = "rocm/pytorch-private:fake-tag"

        with patch("madengine.orchestration.build_orchestrator.DiscoverModels") as mock_dm:
            mock_dm.return_value.run.return_value = fake_models_two_sglang_disagg
            # _save_deployment_config writes a sidecar file we don't care about;
            # patch it to a no-op so we don't depend on its filesystem behavior.
            with patch.object(orch, "_save_deployment_config", return_value=None):
                orch._execute_with_prebuilt_image(use_image=use_image, manifest_output=str(manifest_path))

        manifest = json.loads(manifest_path.read_text())

        assert set(manifest["built_images"].keys()) == set(manifest["built_models"].keys()), (
            "built_images and built_models must share the same key set"
        )
        assert set(manifest["built_models"].keys()) == {"pyt_fake_a", "pyt_fake_b"}

        for model_name in ("pyt_fake_a", "pyt_fake_b"):
            assert manifest["built_images"][model_name]["docker_image"] == use_image
            assert manifest["built_images"][model_name]["prebuilt"] is True
            assert manifest["built_models"][model_name]["env_vars"]["DOCKER_IMAGE_NAME"] == use_image

    def test_multi_model_nested_dict_distributed_does_not_raise(
        self, tmp_path, fake_models_two_sglang_disagg
    ):
        """Copilot C3: `distinct_distributed` / `distinct_slurm` dedupe must not
        TypeError when distributed/slurm blocks contain nested dicts. Before
        the fix, `tuple(sorted((m.get('distributed') or {}).items()))` raised
        `TypeError: unhashable type: 'dict'` because the dict values aren't
        hashable when stuffed into a set."""
        orch = self._build_orchestrator_stub(tmp_path)
        manifest_path = tmp_path / "build_manifest.json"

        with patch("madengine.orchestration.build_orchestrator.DiscoverModels") as mock_dm:
            mock_dm.return_value.run.return_value = fake_models_two_sglang_disagg
            with patch.object(orch, "_save_deployment_config", return_value=None):
                # Must not raise TypeError
                orch._execute_with_prebuilt_image(
                    use_image="rocm/pytorch-private:fake-tag",
                    manifest_output=str(manifest_path),
                )

        # Manifest should still be valid JSON with both models present
        manifest = json.loads(manifest_path.read_text())
        assert len(manifest["built_models"]) == 2


# ---------------------------------------------------------------------------
# 5. xP/yD skip-if-set: model card wins over distributed.sglang_disagg

class TestXpYdSkipIfSet:
    """xP/yD in model card env_vars must not be overwritten by distributed.sglang_disagg."""

    @pytest.fixture
    def slurm_deployment(self, tmp_path: Path) -> SlurmDeployment:
        """SlurmDeployment with model card that has xP=2/yD=3 while sglang_disagg says 1/1."""
        model_info = {
            **PR186_MODEL_ENTRY,
            "env_vars": {**PR186_MODEL_ENTRY["env_vars"], "xP": "2", "yD": "3"},
            "distributed": {
                **PR186_MODEL_ENTRY["distributed"],
                "sglang_disagg": {"prefill_nodes": 1, "decode_nodes": 1},
            },
        }
        script_abs = tmp_path / PR186_MODEL_ENTRY["scripts"]
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n")

        image_key = "rocm/pytorch-private:sglang_disagg_mori_20260502"
        manifest = {
            "built_images": {image_key: {"image_name": image_key, "docker_image": image_key}},
            "built_models": {image_key: model_info},
            "context": {
                "docker_env_vars": {}, "docker_mounts": {}, "docker_build_arg": {},
                "gpu_vendor": "AMD", "guest_os": "UBUNTU", "docker_gpus": "all",
            },
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        additional_context = {
            "deploy": "slurm",
            "gpu_vendor": "AMD",
            "guest_os": "UBUNTU",
            "slurm": dict(PR186_MODEL_ENTRY["slurm"], output_dir=str(tmp_path / "slurm_results")),
            "distributed": model_info["distributed"],
        }
        cfg = DeploymentConfig(target="slurm", manifest_file=str(manifest_path),
                               additional_context=additional_context)
        return SlurmDeployment(cfg)

    def test_model_card_xp_yd_wins(self, slurm_deployment):
        """When env_vars already contains xP/yD, distributed.sglang_disagg must not override them."""
        slurm_deployment.prepare()
        script_text = Path(slurm_deployment.script_path).read_text()

        assert f"export xP={shlex.quote('2')}" in script_text, "model card xP=2 must not be overwritten"
        assert f"export yD={shlex.quote('3')}" in script_text, "model card yD=3 must not be overwritten"
        assert f"export xP={shlex.quote('1')}" not in script_text, "distributed.sglang_disagg xP=1 must not win"
        assert f"export yD={shlex.quote('1')}" not in script_text, "distributed.sglang_disagg yD=1 must not win"


# ---------------------------------------------------------------------------
# 6. _execute_build_on_compute manifest-shape contract (multi-model parity)

class TestBuildOnComputeManifestShape:
    """_execute_build_on_compute must produce the same key contract as _execute_with_prebuilt_image.

    built_images.keys() == built_models.keys() == set of model names, so
    ContainerRunner.run_models_from_manifest() can join them.
    """

    def _build_orchestrator_stub(self, tmp_path: Path):
        from madengine.orchestration.build_orchestrator import BuildOrchestrator
        orch = BuildOrchestrator.__new__(BuildOrchestrator)
        orch.args = MagicMock()
        orch.console = MagicMock()
        orch.rich_console = MagicMock()
        orch.context = MagicMock()
        orch.context.ctx = {}
        orch.additional_context = {"slurm": {"partition": "gpu", "time": "01:00:00"}}
        orch._original_user_slurm_keys = set()
        orch.credentials = {}
        return orch

    def test_two_model_manifest_keys_match(self, tmp_path):
        """built_images and built_models must share the same key set (model names)."""
        fake_models = [
            {
                "name": "model_a",
                "dockerfile": "docker/model_a",
                "scripts": "scripts/model_a/run.sh",
                "n_gpus": "8",
                "tags": ["model_a"],
                "slurm": {"partition": "gpu", "time": "01:00:00"},
                "distributed": {"launcher": "slurm_multi"},
                "env_vars": {},
            },
            {
                "name": "model_b",
                "dockerfile": "docker/model_b",
                "scripts": "scripts/model_b/run.sh",
                "n_gpus": "8",
                "tags": ["model_b"],
                "slurm": {"partition": "gpu", "time": "01:00:00"},
                "distributed": {"launcher": "slurm_multi"},
                "env_vars": {},
            },
        ]
        # Write dummy Dockerfiles so glob finds them
        for m in fake_models:
            df = tmp_path / f"{m['dockerfile']}.ubuntu.amd.Dockerfile"
            df.parent.mkdir(parents=True, exist_ok=True)
            df.write_text("FROM scratch\n")

        manifest_path = tmp_path / "build_manifest.json"
        orch = self._build_orchestrator_stub(tmp_path)

        import os
        orig_cwd = os.getcwd()
        try:
            os.chdir(tmp_path)
            with patch("madengine.orchestration.build_orchestrator.DiscoverModels") as mock_dm:
                mock_dm.return_value.run.return_value = fake_models
                with patch("subprocess.run") as mock_run:
                    mock_run.return_value = MagicMock(returncode=0)
                    # Use localhost:5000 (private-registry path) so the test
                    # doesn't hit the public-registry credential gate at
                    # build_orchestrator.py:954. The manifest-shape contract
                    # this test locks in is registry-agnostic.
                    orch._execute_build_on_compute(
                        registry="localhost:5000/myrepo",
                        manifest_output=str(manifest_path),
                    )
        finally:
            os.chdir(orig_cwd)

        manifest = json.loads(manifest_path.read_text())
        assert set(manifest["built_images"].keys()) == set(manifest["built_models"].keys()), (
            "built_images and built_models must share the same key set"
        )
        assert set(manifest["built_models"].keys()) == {"model_a", "model_b"}
        for mn in ("model_a", "model_b"):
            assert manifest["built_models"][mn]["built_on_compute"] is True
            assert "DOCKER_IMAGE_NAME" in manifest["built_models"][mn]["env_vars"]


# ---------------------------------------------------------------------------
# 6. SGLang-disagg default split topology
# ---------------------------------------------------------------------------
class TestSglangDisaggDefaultSplit:
    """`_generate_sglang_disagg_command` must produce a valid prefill/decode
    split for the default (no custom prefill/decode) path, including the
    co-located-proxy minimum of nnodes=2."""

    @pytest.fixture
    def deployment_factory(self, tmp_path: Path):
        """Build a SlurmDeployment with no custom sglang_disagg split, so
        `_generate_sglang_disagg_command` takes the default-split branch."""
        manifest = {
            "built_images": {},
            "built_models": {},
            "context": {},
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context={
                "deploy": "slurm",
                "slurm": {"output_dir": str(tmp_path / "slurm_results")},
            },
        )
        return SlurmDeployment(cfg)

    @staticmethod
    def _parse_split(script: str):
        """Extract (xP, yD, total) from the exported topology env vars."""
        xP = yD = total = None
        for line in script.splitlines():
            line = line.strip()
            if line.startswith("export SGLANG_DISAGG_PREFILL_NODES="):
                xP = int(line.split("=", 1)[1])
            elif line.startswith("export SGLANG_DISAGG_DECODE_NODES="):
                yD = int(line.split("=", 1)[1])
            elif line.startswith("export SGLANG_DISAGG_TOTAL_NODES="):
                total = int(line.split("=", 1)[1])
        return xP, yD, total

    def test_default_split_two_nodes_is_co_located(self, deployment_factory):
        """nnodes=2 default split must be co-located (xP=1, yD=1), not yD=0."""
        script = deployment_factory._generate_sglang_disagg_command(
            nnodes=2, nproc_per_node=8, master_port=12345
        )
        xP, yD, total = self._parse_split(script)
        assert (xP, yD, total) == (1, 1, 2), f"expected xP=1,yD=1,total=2, got {(xP, yD, total)}"

    @pytest.mark.parametrize("nnodes", [2, 3, 4, 5, 6, 8])
    def test_default_split_always_has_prefill_and_decode(self, deployment_factory, nnodes):
        """Every supported nnodes must yield at least one prefill and one decode node."""
        script = deployment_factory._generate_sglang_disagg_command(
            nnodes=nnodes, nproc_per_node=8, master_port=12345
        )
        xP, yD, _ = self._parse_split(script)
        assert xP >= 1, f"prefill nodes must be >= 1 for nnodes={nnodes}, got {xP}"
        assert yD >= 1, f"decode nodes must be >= 1 for nnodes={nnodes}, got {yD}"

    def test_below_minimum_nodes_raises(self, deployment_factory):
        """nnodes < 2 must raise ValueError (minimum cluster size)."""
        with pytest.raises(ValueError):
            deployment_factory._generate_sglang_disagg_command(
                nnodes=1, nproc_per_node=8, master_port=12345
            )


# ---------------------------------------------------------------------------
# 6. Path-parity contract: the model card drives the allocation and the launcher
#
# slurm_multi is an escape hatch, not a second product. These lock in the pieces
# of the model-card contract that the templated path already honoured and the
# self-managed path silently dropped.

from madengine.deployment.common import (  # noqa: E402
    resolve_launcher_from_sources,
    resolve_node_count,
)


class TestResolveNodeCount:
    """slurm.nodes and distributed.nnodes reconcile into one allocation size."""

    def test_nnodes_absent_keeps_configured(self):
        assert resolve_node_count(1, None, False) == (1, None)

    def test_nnodes_sizes_allocation_when_nodes_defaulted(self):
        """The bug this fixes: a card declaring only nnodes ran on the nodes=1 default."""
        nodes, note = resolve_node_count(1, 4, nodes_explicitly_set=False)
        assert nodes == 4
        assert note and "distributed.nnodes=4" in note

    def test_agreement_is_silent(self):
        assert resolve_node_count(4, 4, nodes_explicitly_set=True) == (4, None)

    def test_explicit_nodes_wins_conflict_but_warns(self):
        """Never silently allocate more nodes than the user asked to be billed for."""
        nodes, note = resolve_node_count(6, 4, nodes_explicitly_set=True)
        assert nodes == 6
        assert note and "conflicts" in note

    @pytest.mark.parametrize("bad", ["bad", "", [], {}])
    def test_non_numeric_nnodes_falls_back(self, bad):
        nodes, note = resolve_node_count(2, bad, nodes_explicitly_set=False)
        assert nodes == 2
        if bad != "":
            assert note is not None

    @pytest.mark.parametrize("bad", [0, -1, "0", "-1"])
    def test_non_positive_nnodes_falls_back(self, bad):
        """sbatch cannot schedule --nodes=0; reject it here, not at submit time."""
        nodes, note = resolve_node_count(2, bad, nodes_explicitly_set=False)
        assert nodes == 2
        assert note and ">= 1" in note

    def test_non_positive_nnodes_does_not_override_explicit_nodes(self):
        nodes, note = resolve_node_count(4, 0, nodes_explicitly_set=True)
        assert nodes == 4
        assert note is not None

    def test_idempotent_across_repeated_resolution(self):
        """deploy() re-runs prepare() after preflight; resolution must not ratchet."""
        nodes, _ = resolve_node_count(1, 4, nodes_explicitly_set=False)
        again, _ = resolve_node_count(1, 4, nodes_explicitly_set=False)
        assert nodes == again == 4


class TestResolveLauncherFromSources:
    """One resolver for both dispatch sites, deployment config first."""

    def test_deployment_config_wins(self):
        assert resolve_launcher_from_sources("vllm", "slurm_multi") == "vllm"

    def test_falls_back_to_model_card(self):
        assert resolve_launcher_from_sources(None, "slurm_multi") == "slurm_multi"

    def test_default_when_neither_declared(self):
        assert resolve_launcher_from_sources(None, None) == "torchrun"

    @pytest.mark.parametrize("deployment,card,expected", [
        (None, "vllm", "vllm"),
        ("sglang", "vllm", "sglang"),
        (None, None, "torchrun"),
        ("sglang", None, "sglang"),
        ("slurm_multi", "torchrun", "slurm_multi"),
        # A falsy deployment value is "not declared", not "declared as empty":
        # ConfigLoader materializes distributed.launcher as "" when the preset
        # carries the key but neither the user nor the card filled it in.
        ("", "slurm_multi", "slurm_multi"),
        ("", None, "torchrun"),
    ])
    def test_dispatch_and_env_block_cannot_disagree(self, deployment, card, expected):
        """
        prepare() used to read the card while _prepare_template_context() read the
        deployment config, so a card-declared launcher could pick one path and emit
        another path's env block. Both now call this, so they agree by construction.
        """
        assert resolve_launcher_from_sources(deployment, card) == expected


class TestExplicitSlurmKeysManifestProvenance:
    """A manifest's slurm dict is written *after* ConfigLoader applies preset
    defaults, so inferring "explicit" from which keys are present in the manifest
    would treat a persisted default (e.g. nodes=1) as if the user or model card had
    set it. BuildOrchestrator records real provenance as "_explicit_slurm_keys" in
    deployment_config; SlurmDeployment must prefer that over inferring from keys.
    """

    def _deployment(self, tmp_path: Path, additional_context: dict) -> SlurmDeployment:
        manifest = {"built_images": {}, "built_models": {}, "context": {}}
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))
        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context=additional_context,
        )
        return SlurmDeployment(cfg)

    def test_persisted_default_is_not_treated_as_explicit(self, tmp_path):
        """Regression: slurm.nodes=1 came from a ConfigLoader preset default at build
        time, not from the user or model card, so distributed.nnodes must still win."""
        d = self._deployment(tmp_path, {
            "slurm": {"nodes": 1, "output_dir": str(tmp_path / "slurm_results")},
            "distributed": {"nnodes": 4},
            "_explicit_slurm_keys": ["output_dir"],
        })
        assert "nodes" not in d._explicit_slurm_keys
        assert d.nodes == 4

    def test_manifest_provenance_respects_real_explicit_conflict(self, tmp_path):
        """When the manifest says slurm.nodes really was explicit, an explicit
        conflict with distributed.nnodes must still win (with a warning)."""
        d = self._deployment(tmp_path, {
            "slurm": {"nodes": 6, "output_dir": str(tmp_path / "slurm_results")},
            "distributed": {"nnodes": 4},
            "_explicit_slurm_keys": ["nodes", "output_dir"],
        })
        assert "nodes" in d._explicit_slurm_keys
        assert d.nodes == 6

    def test_falls_back_to_key_inference_without_manifest_provenance(self, tmp_path):
        """Direct --additional-context (no manifest round trip) has no
        "_explicit_slurm_keys" key; behavior falls back to inferring from the
        slurm dict's own keys, as before this fix."""
        d = self._deployment(tmp_path, {
            "slurm": {"nodes": 6, "output_dir": str(tmp_path / "slurm_results")},
            "distributed": {"nnodes": 4},
        })
        assert d._explicit_slurm_keys == {"nodes", "output_dir"}
        assert d.nodes == 6


class TestSlurmMultiDeclaredResultsCsv:
    """A slurm_multi card's `multiple_results` names its own results CSV."""

    @pytest.fixture
    def deployment(self, tmp_path: Path) -> SlurmDeployment:
        script_rel = "scripts/wl/run.slurm"
        script_abs = tmp_path / script_rel
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n")

        model = {
            "name": "wl",
            "scripts": script_rel,
            "multiple_results": "perf_WL.csv",
            "distributed": {"launcher": "slurm_multi"},
        }
        manifest = {
            "built_images": {},
            "built_models": {"img:tag": model},
            "context": {},
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))
        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context={
                "slurm": {"output_dir": str(tmp_path / "slurm_results")},
                "distributed": {"launcher": "slurm_multi"},
            },
        )
        d = SlurmDeployment(cfg)
        d._model_for_test = model
        d._script_dir_for_test = script_abs.parent
        return d

    def test_finds_csv_next_to_model_script(self, deployment):
        """The wrapper cd's to the script dir, so $(pwd) writes land there."""
        target = deployment._script_dir_for_test / "perf_WL.csv"
        target.write_text("model,performance,metric\nwl,1.0,tok/s\n")
        found = deployment._slurm_multi_declared_result_csv(
            deployment._model_for_test, "12345"
        )
        assert found == target

    def test_ignores_empty_file(self, deployment):
        (deployment._script_dir_for_test / "perf_WL.csv").write_text("")
        assert deployment._slurm_multi_declared_result_csv(
            deployment._model_for_test, "12345"
        ) is None

    def test_returns_none_without_declaration(self, deployment):
        assert deployment._slurm_multi_declared_result_csv({"name": "wl"}, "12345") is None

    def test_returns_none_when_model_info_missing(self, deployment):
        assert deployment._slurm_multi_declared_result_csv(None, "12345") is None


class TestSlurmMultiPerfAggregation:
    """Aggregating the per-job CSV into cwd/perf.csv must not append it to itself."""

    @pytest.fixture
    def deployment(self, tmp_path: Path) -> SlurmDeployment:
        manifest = {"built_images": {}, "built_models": {}, "context": {}}
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))
        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context={"slurm": {"output_dir": str(tmp_path / "slurm_results")}},
        )
        d = SlurmDeployment(cfg)
        d.output_dir.mkdir(parents=True, exist_ok=True)
        return d

    def test_cwd_perf_source_is_not_duplicated(self, deployment, tmp_path, monkeypatch):
        """
        The <cwd>/perf.csv fallback (and a card declaring multiple_results:
        "perf.csv") makes source and destination the same file. Appending it to
        itself would double every row on each collection.
        """
        monkeypatch.chdir(tmp_path)
        rows = "model,performance,metric,status\nwl,1.0,tok/s,SUCCESS\n"
        Path("perf.csv").write_text(rows)

        deployment._collect_slurm_multi_results(
            "12345", {"perf_files": [], "logs": [], "successful_runs": [], "failed_runs": []}, None
        )

        assert Path("perf.csv").read_text() == rows

    def test_distinct_source_is_appended(self, deployment, tmp_path, monkeypatch):
        """A genuinely separate per-job CSV still aggregates, minus its header."""
        monkeypatch.chdir(tmp_path)
        Path("perf.csv").write_text("model,performance,metric,status\nold,1.0,tok/s,SUCCESS\n")
        job_csv = tmp_path / "job" / "perf.csv"
        job_csv.parent.mkdir()
        job_csv.write_text("model,performance,metric,status\nnew,2.0,tok/s,SUCCESS\n")
        deployment.slurm_config["results_dir"] = str(job_csv.parent)

        deployment._collect_slurm_multi_results(
            "12345", {"perf_files": [], "logs": [], "successful_runs": [], "failed_runs": []}, None
        )

        text = Path("perf.csv").read_text()
        assert "old,1.0" in text and "new,2.0" in text
        assert text.count("model,performance") == 1


# ---------------------------------------------------------------------------
# 7. require_pinned_image on the slurm_multi wrapper

DIGEST = "sha256:" + "df36ef7e" * 8


class TestSlurmMultiRequirePinnedImage:
    """slurm_multi wrapper pins DOCKER_IMAGE_NAME (and thus the pull) when required."""

    IMAGE_KEY = "rocm/pytorch-private:sglang_disagg_mori_20260502"

    def _deployment(self, tmp_path, require_pinned, image_digest):
        script_rel = PR186_MODEL_ENTRY["scripts"]
        script_abs = tmp_path / script_rel
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n# placeholder\n")

        image_entry = {
            "image_name": self.IMAGE_KEY,
            "docker_image": self.IMAGE_KEY,
            "registry_image": self.IMAGE_KEY,
        }
        if image_digest:
            image_entry["image_digest"] = image_digest

        manifest = {
            "built_images": {self.IMAGE_KEY: image_entry},
            "built_models": {self.IMAGE_KEY: PR186_MODEL_ENTRY},
            "context": {
                "docker_env_vars": {},
                "docker_mounts": {},
                "docker_build_arg": {},
                "gpu_vendor": "AMD",
                "guest_os": "UBUNTU",
                "docker_gpus": "all",
            },
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        additional_context = {
            "deploy": "slurm",
            "gpu_vendor": "AMD",
            "guest_os": "UBUNTU",
            "slurm": dict(
                PR186_MODEL_ENTRY["slurm"], output_dir=str(tmp_path / "slurm_results")
            ),
            "distributed": PR186_MODEL_ENTRY["distributed"],
        }
        if require_pinned:
            additional_context["require_pinned_image"] = True

        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context=additional_context,
        )
        return SlurmDeployment(cfg)

    def test_default_exports_tag(self, tmp_path):
        dep = self._deployment(tmp_path, require_pinned=False, image_digest=DIGEST)
        assert dep.prepare() is True
        script_text = Path(dep.script_path).read_text()
        assert f"export DOCKER_IMAGE_NAME={shlex.quote(self.IMAGE_KEY)}" in script_text
        assert DIGEST not in script_text

    def test_enabled_exports_pinned_reference(self, tmp_path):
        dep = self._deployment(tmp_path, require_pinned=True, image_digest=DIGEST)
        assert dep.prepare() is True
        script_text = Path(dep.script_path).read_text()

        pinned = f"rocm/pytorch-private@{DIGEST}"
        assert f"export DOCKER_IMAGE_NAME={shlex.quote(pinned)}" in script_text
        # The parallel pull interpolates the same value, so it is pinned too.
        assert f"docker pull {pinned}" in script_text

    def test_enabled_without_digest_does_not_silently_fall_through(self, tmp_path):
        """A missing digest must abort, not quietly take the standard template path.

        prepare()'s launcher peek wraps the slurm_multi dispatch in a bare
        `except Exception: pass`. Without the re-raise, a ConfigurationError
        here would be swallowed and prepare() would generate an ordinary
        (unpinned) sbatch script instead — the exact silent degradation the
        flag exists to prevent.
        """
        dep = self._deployment(tmp_path, require_pinned=True, image_digest=None)
        with pytest.raises(ConfigurationError):
            dep.prepare()


# ---------------------------------------------------------------------------
# 13. Accounting directives and module loads on the self-managed path
# ---------------------------------------------------------------------------
class TestSlurmMultiAccountingDirectives:
    """`qos`, `account` and `modules` are part of the declared parity set, so the
    slurm_multi wrapper must emit them like job.sh.j2 does. Before this, they were
    promoted into deployment_config and then silently dropped: a card declaring
    them produced a wrapper with no `#SBATCH --account/--qos` and no `module load`,
    which a billing-enforced site rejects outright.
    """

    def _deployment(self, tmp_path: Path, **slurm_overrides) -> SlurmDeployment:
        script_rel = PR186_MODEL_ENTRY["scripts"]
        script_abs = tmp_path / script_rel
        script_abs.parent.mkdir(parents=True, exist_ok=True)
        script_abs.write_text("#!/bin/bash\n")

        image_key = "rocm/pytorch-private:sglang_disagg_mori_20260502"
        manifest = {
            "built_images": {image_key: {"docker_image": image_key}},
            "built_models": {image_key: PR186_MODEL_ENTRY},
            "context": {},
        }
        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps(manifest))

        slurm = dict(
            PR186_MODEL_ENTRY["slurm"],
            output_dir=str(tmp_path / "slurm_results"),
            **slurm_overrides,
        )
        cfg = DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context={
                "deploy": "slurm",
                "slurm": slurm,
                "distributed": PR186_MODEL_ENTRY["distributed"],
            },
        )
        return SlurmDeployment(cfg)

    def _script(self, dep: SlurmDeployment) -> str:
        assert dep.prepare() is True
        return Path(dep.script_path).read_text()

    def test_qos_and_account_emitted(self, tmp_path):
        text = self._script(self._deployment(tmp_path, qos="high", account="amd-ml"))
        assert "#SBATCH --qos=high" in text
        assert "#SBATCH --account=amd-ml" in text

    def test_modules_loaded(self, tmp_path):
        text = self._script(
            self._deployment(tmp_path, modules=["rocm/6.2", "openmpi"])
        )
        assert "module load rocm/6.2" in text
        assert "module load openmpi" in text

    def test_modules_load_before_model_script(self, tmp_path):
        """`module load` has to run before the model script, or the site's
        docker/rocm binaries are missing from PATH for its internal srun calls."""
        text = self._script(self._deployment(tmp_path, modules=["rocm/6.2"]))
        lines = text.splitlines()
        module_idx = next(i for i, l in enumerate(lines) if l == "module load rocm/6.2")
        script_idx = next(
            i for i, l in enumerate(lines) if "run_xPyD_models.slurm" in l and l.startswith("bash ")
        )
        assert module_idx < script_idx

    def test_sbatch_directives_stay_in_header_block(self, tmp_path):
        """sbatch stops parsing directives at the first non-comment line, so
        --qos/--account must precede the `set -e` body."""
        text = self._script(self._deployment(tmp_path, qos="high", account="amd-ml"))
        lines = text.splitlines()
        first_body = next(
            i for i, l in enumerate(lines)
            if l.strip() and not l.startswith("#") and not l.startswith("#!")
        )
        for directive in ("#SBATCH --qos=high", "#SBATCH --account=amd-ml"):
            assert lines.index(directive) < first_body

    def test_absent_fields_emit_nothing(self, tmp_path):
        """No declaration must not produce an empty directive that sbatch rejects."""
        text = self._script(self._deployment(tmp_path))
        assert "--qos" not in text
        assert "--account" not in text
        assert "module load" not in text


# ---------------------------------------------------------------------------
# 14. build-on-compute parity with the other build paths
# ---------------------------------------------------------------------------
class TestBuildOnComputeModelFieldParity:
    """--build-on-compute writes its own manifest and returns, so it used to skip
    _merge_model_config_into_manifest entirely. That lost the model card's declared
    results CSV, recorded no "_explicit_slurm_keys" provenance, and let the
    post-ConfigLoader preset defaults in --additional-context outrank the card.
    """

    CARD = {
        "name": "model_a",
        "dockerfile": "docker/model_a",
        "scripts": "scripts/model_a/run.slurm",
        "n_gpus": "8",
        "tags": ["model_a"],
        "multiple_results": "perf_model_a.csv",
        "slurm": {"partition": "amd-rccl", "nodes": 4, "time": "01:00:00"},
        "distributed": {"launcher": "slurm_multi", "nnodes": 4},
        "env_vars": {},
    }

    def _run_build_on_compute(self, tmp_path: Path, card: dict, context_slurm: dict,
                              user_slurm_keys: set) -> dict:
        from madengine.orchestration.build_orchestrator import BuildOrchestrator

        orch = BuildOrchestrator.__new__(BuildOrchestrator)
        orch.args = MagicMock()
        orch.console = MagicMock()
        orch.rich_console = MagicMock()
        orch.context = MagicMock()
        orch.context.ctx = {}
        # Post-ConfigLoader: carries preset defaults alongside the user's own keys.
        orch.additional_context = {"slurm": context_slurm}
        orch._original_user_slurm_keys = set(user_slurm_keys)
        orch.credentials = {}

        df = tmp_path / f"{card['dockerfile']}.ubuntu.amd.Dockerfile"
        df.parent.mkdir(parents=True, exist_ok=True)
        df.write_text("FROM scratch\n")

        manifest_path = tmp_path / "build_manifest.json"
        import os
        orig_cwd = os.getcwd()
        try:
            os.chdir(tmp_path)
            with patch("madengine.orchestration.build_orchestrator.DiscoverModels") as mock_dm:
                mock_dm.return_value.run.return_value = [card]
                with patch("subprocess.run") as mock_run:
                    mock_run.return_value = MagicMock(returncode=0)
                    orch._execute_build_on_compute(
                        registry="localhost:5000/myrepo",
                        manifest_output=str(manifest_path),
                    )
        finally:
            os.chdir(orig_cwd)
        return json.loads(manifest_path.read_text())

    def test_declared_results_csv_is_persisted(self, tmp_path):
        """Without multiple_results the run has no declared CSV to collect and
        falls back to log scraping, which a slurm_multi model produces nothing for."""
        manifest = self._run_build_on_compute(
            tmp_path, self.CARD,
            context_slurm={"partition": "amd-rccl", "nodes": 1},
            user_slurm_keys={"partition"},
        )
        assert manifest["built_models"]["model_a"]["multiple_results"] == "perf_model_a.csv"

    def test_preset_default_does_not_outrank_model_card(self, tmp_path):
        """nodes=1 is a ConfigLoader preset default, not a user choice, so the
        card's nodes=4 must survive into the persisted slurm config."""
        manifest = self._run_build_on_compute(
            tmp_path, self.CARD,
            context_slurm={"partition": "amd-rccl", "nodes": 1, "time": "24:00:00"},
            user_slurm_keys={"partition"},
        )
        slurm = manifest["deployment_config"]["slurm"]
        assert slurm["nodes"] == 4
        assert slurm["time"] == "01:00:00"

    def test_user_explicit_key_still_wins_over_model_card(self, tmp_path):
        manifest = self._run_build_on_compute(
            tmp_path, self.CARD,
            context_slurm={"partition": "amd-rccl", "nodes": 2},
            user_slurm_keys={"partition", "nodes"},
        )
        assert manifest["deployment_config"]["slurm"]["nodes"] == 2

    def test_explicit_slurm_keys_provenance_is_recorded(self, tmp_path):
        manifest = self._run_build_on_compute(
            tmp_path, self.CARD,
            context_slurm={"partition": "amd-rccl", "nodes": 1, "time": "24:00:00"},
            user_slurm_keys={"partition"},
        )
        explicit = set(manifest["deployment_config"]["_explicit_slurm_keys"])
        # partition: user. nodes/time: declared by the card.
        assert {"partition", "nodes", "time"} <= explicit

    def test_undeclared_preset_default_is_not_marked_explicit(self, tmp_path):
        """The card says nothing about nodes, so the persisted nodes=1 is a preset
        default and distributed.nnodes must still be free to size the allocation."""
        card = dict(self.CARD, slurm={"partition": "amd-rccl"})
        manifest = self._run_build_on_compute(
            tmp_path, card,
            context_slurm={"partition": "amd-rccl", "nodes": 1},
            user_slurm_keys={"partition"},
        )
        assert "nodes" not in set(manifest["deployment_config"]["_explicit_slurm_keys"])

    def test_model_card_distributed_reaches_deployment_config(self, tmp_path):
        """run --manifest-file infers the SLURM target from deployment_config."""
        manifest = self._run_build_on_compute(
            tmp_path, self.CARD,
            context_slurm={"partition": "amd-rccl", "nodes": 1},
            user_slurm_keys={"partition"},
        )
        assert manifest["deployment_config"]["distributed"]["launcher"] == "slurm_multi"


# ---------------------------------------------------------------------------
# 15. Runtime slurm override must not inherit stale provenance
# ---------------------------------------------------------------------------
class TestRuntimeSlurmOverrideProvenance:
    """_load_and_merge_manifest replaces the manifest's slurm block with the
    runtime one but used to leave "_explicit_slurm_keys" describing the *old*
    block, so a build-time explicit nodes marked the runtime default nodes=1 as
    deliberate and silently suppressed distributed.nnodes.
    """

    def _merge(self, tmp_path: Path, stored: dict, runtime: dict) -> dict:
        from madengine.orchestration.run_orchestrator import RunOrchestrator

        orch = RunOrchestrator.__new__(RunOrchestrator)
        orch.rich_console = MagicMock()
        orch.additional_context = runtime

        manifest_path = tmp_path / "build_manifest.json"
        manifest_path.write_text(json.dumps({
            "built_images": {}, "built_models": {}, "context": {},
            "deployment_config": stored,
        }))
        orch._load_and_merge_manifest(str(manifest_path))
        return json.loads(manifest_path.read_text())["deployment_config"]

    def test_runtime_slurm_recomputes_provenance(self, tmp_path):
        cfg = self._merge(
            tmp_path,
            stored={
                "slurm": {"partition": "old", "nodes": 2},
                "_explicit_slurm_keys": ["nodes", "partition"],
                "distributed": {"nnodes": 4},
            },
            runtime={"slurm": {"partition": "new"}},
        )
        assert cfg["_explicit_slurm_keys"] == ["partition"]

    def test_stale_provenance_no_longer_suppresses_nnodes(self, tmp_path):
        """End of the chain: the recomputed provenance must let SlurmDeployment
        size the allocation from distributed.nnodes."""
        cfg = self._merge(
            tmp_path,
            stored={
                "slurm": {"partition": "old", "nodes": 2},
                "_explicit_slurm_keys": ["nodes", "partition"],
            },
            runtime={"slurm": {"partition": "new"}, "distributed": {"nnodes": 4}},
        )
        manifest_path = tmp_path / "m.json"
        manifest_path.write_text(json.dumps({"built_images": {}, "built_models": {}, "context": {}}))
        dep = SlurmDeployment(DeploymentConfig(
            target="slurm",
            manifest_file=str(manifest_path),
            additional_context={
                "slurm": dict(cfg["slurm"], output_dir=str(tmp_path / "out")),
                "distributed": cfg["distributed"],
                "_explicit_slurm_keys": cfg["_explicit_slurm_keys"],
            },
        ))
        assert "nodes" not in dep._explicit_slurm_keys
        assert dep.nodes == 4

    def test_provenance_untouched_without_runtime_slurm(self, tmp_path):
        """A plain `run --manifest-file` must keep the build-time provenance."""
        cfg = self._merge(
            tmp_path,
            stored={
                "slurm": {"partition": "old", "nodes": 2},
                "_explicit_slurm_keys": ["nodes", "partition"],
            },
            runtime={"env_vars": {"FOO": "1"}},
        )
        assert cfg["_explicit_slurm_keys"] == ["nodes", "partition"]
        assert cfg["slurm"]["nodes"] == 2
